using Microsoft.AspNetCore.Mvc;
using Shukachi.SeedAgent.Api.Models;

namespace Shukachi.SeedAgent.Api.Controllers
{
    [ApiController]
    [Route("")]
    public sealed class TextController : ControllerBase
    {
        [HttpPost("text")]
        public ActionResult<TextResponse> PostText([FromBody] TextRequest request)
        {
            var response = new TextResponse
            {
                Response = $"Mock response for: {request.Text}",
                References = [],
                Reasoning = "Mock response generated by seed agent."
            };

            return Ok(response);
        }
    }
}
