@baseUrl = http://localhost:3000

###
POST {{baseUrl}}/text
Content-Type: application/json

{
  "text": "# Створення модулів\n\nЗаписати створення модуля в Мавці можна так:\n\n```\nмавка\nмодуль\n  якийсь_предмет = 2.10\n\n  дати якийсь_предмет\nкінець\n```\n\nЯкщо додати назву до цього запису, то після створення, модуль буде відразу визнане в поточній діяльності:\n\n```\nмавка\nмодуль якийсь_модуль\n  якийсь_предмет = 2.10\n\n  дати якийсь_предмет\nкінець\n```",
  "uid": "c9b941b7-6c71-449b-8fd2-15b53d97edb0"
}